---
title: "Short Courses"
output:
  html_document:
    theme: cosmo
---


```{=html}
<style type="text/css">
h1.title {
  font-size: 36px;
  color: DarkRed;
  text-align: center;
}
</style>
```


<h3 style="color: DarkRed; text-align: left;">
Course 1: Practitioner’s View of Adaptive Designs
</h3>

**Course tutors**: [Prof. Tim Friede](https://medstat.umg.eu/en/friede/) (Department of Medical Statistics, University of Gottingen), [Dr. Hiya Banerjee](https://www.linkedin.com/in/hiya-b-22397514/)(Eli Lilly) <br/>

**Time**: 1st June 2026, 9 am- 12:30 pm <br/>

**Location**: Stephenson Building, Newcastle University


**Course summary**:  Drug development is becoming increasingly resource and time consuming with many compounds failing in later stages. Adaptive designs for clinical trials were identified as a means to make the clinical development of therapies more efficient. Furthermore, adaptive designs can be used to make trials more robust against misspecifications in the planning phase. Focussing on late development phases (i.e. phases 2 and 3) and in particular confirmatory trials, we start by providing an overview of adaptive design methodology and relevant regulatory guidance including the new ICH E20. Monte Carlo simulations are commonly used to select development strategies and trial designs as well as to optimize such strategies and designs. We provide an introduction to R package for clinical trial simulation and optimization. Furthermore, the Clinical Scenario Evaluation framework is introduced as a framework to structure simulations and their reports. Also, implications of adaptive designs on study protocols and statistical analysis plans are discussed. We close with comments on the role of data monitoring committees in adaptive designs. 



<h3 style="color: DarkRed; text-align: left;">
Course 2: Designing better trials: Advanced randomization methods for modern clinical research 
</h3>

**Course Tutors**: Randomisation Working Group lead by [Alex Sverdlov](https://www.linkedin.com/in/alex-sverdlov-a403167/) (Novartis)

**Time**: 1st June 2026, 2 pm- 5:30 pm <br/>

**Location**: Stephenson Building, Newcastle University


**Course summary**: Modern clinical trials increasingly demand sophisticated randomization methods to efficiently investigate multiple treatments across diverse patient populations while adhering to stringent regulatory requirements. This intensive one-day short course offers hands-on training in state-of-the-art restricted randomization designs, equipping participants with the practical skills and conceptual understanding necessary for designing and implementing robust clinical trials. We will delve into various restricted randomization techniques, including those crucial for multi-arm and platform trials, clearly defining their mechanisms and demonstrating their advantages over traditional methods like permuted block randomization. A substantial part of the course will introduce Response-Adaptive Randomization (RAR) designs, focusing on their suitable applications and, critically, current regulatory perspectives and pathways for their acceptance, while acknowledging the time constraints for extensive hands-on simulation. Participants will gain practical experience through computer code examples using established statistical software (e.g., randomizeR; Incertus.jl) and case studies, empowering them to select and implement fit-for-purpose randomization methods to achieve higher statistical efficiency and more ethical clinical trials. For more details see [here](https://admtp.github.io/ADMTP2026/Short Course 2_AS).

**Course fees**
<ul>
  <li> Registration Fees for a single course: £175   </li>
  <li> Registration Fees for both courses: £300   </li>
</ul>

**Registration**: 
Registration for the short course will open with workshop registration.
 
